INSERT INTO USUARIO (USU_ID, USU_NOME, USU_SENHA, EMAIL, FONE, PERFIL, ADMIN_PDV, VENDEDOR, NOME, COMISSAO, ID_VENDEDOR, ATIVO) VALUES (1, 'ADMIN', 'ldesistemas', NULL, NULL, 'Administrador', 'Sim', 'Não', 'ADMIN', NULL, NULL, 'Sim');

COMMIT WORK;
