INSERT INTO USUARIO_GRUPO (DESCRICAO, ATIVO, ACESSO_PDV, ACESSO_OP, ACESSO_FINANCEIRO)
                   VALUES ('PADRAO', 1, 1, 1, 1);
INSERT INTO USUARIO_GRUPO (DESCRICAO, ATIVO, ACESSO_PDV, ACESSO_OP, ACESSO_FINANCEIRO)
                   VALUES ('PDV', 1, 1, 0, 0);

COMMIT WORK;
