INSERT INTO HISTORICO_GRUPO (CODIGO, DESCRI)
                     VALUES (1, 'RECEITAS');
INSERT INTO HISTORICO_GRUPO (CODIGO, DESCRI)
                     VALUES (2, 'CUSTOS');
INSERT INTO HISTORICO_GRUPO (CODIGO, DESCRI)
                     VALUES (3, 'DESPESAS');
INSERT INTO HISTORICO_GRUPO (CODIGO, DESCRI)
                     VALUES (4, 'IMOBILIZADO');
INSERT INTO HISTORICO_GRUPO (CODIGO, DESCRI)
                     VALUES (5, 'OUTRAS');

COMMIT WORK;
