INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (1, '1.001', 'VENDA - DINHEIRO', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (2, '1.002', 'VENDA - CARTÃO DE DÉBITO', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (3, '1.003', 'VENDA - CARTÃO DE CRÉDITO', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (4, '1.004', 'VENDA - CHEQUE', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (5, '1.005', 'VENDA - BOLETO BANCÁRIO', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (6, '1.006', 'JUROS RECEBIDOS', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (7, '1.007', 'DESCONTO OBTIDO', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (8, '1.008', 'REEMBOLSO', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (9, '2.001', 'MATÉRIA PRIMA', 'Débito', 2);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (10, '2.002', 'FOLHA DE PAGAMENTO', 'Débito', 2);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (11, '2.003', 'COMPRA DE MERC. P/ REVENDA', 'Débito', 2);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (12, '2.004', 'FRETES E CARRETOS', 'Débito', 2);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (13, '2.005', 'ENERGIA', 'Débito', 2);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (14, '2.006', 'DAS', 'Débito', 2);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (15, '2.007', 'ICMS', 'Débito', 2);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (16, '2.008', 'PIS', 'Débito', 2);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (17, '2.009', 'COFINS', 'Débito', 2);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (18, '3.001', 'AGUA', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (19, '3.002', 'ALUGUEL', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (20, '3.003', 'SEGURO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (21, '3.004', 'TELEFONE', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (22, '3.005', 'TAXA BANCÁRIA', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (23, '3.006', 'INTERNET', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (24, '3.007', 'MATERIAL DE LIMPEZA', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (25, '3.008', 'ALIMENTAÇÃO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (26, '3.009', 'BENS IRRELEVANTES', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (27, '3.010', 'MATERIAL DE ESCRITÓRIO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (28, '3.011', 'MANUTEÇÃO DE VEÍCULO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (29, '3.012', 'REPAROS NO PRÉDIO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (30, '3.013', 'DESP. C/ VENDAS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (31, '3.014', 'CESTA BÁSICA', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (32, '3.015', 'PROPAGANDA E PUBLICIDADE', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (33, '3.016', 'COMBUSTÍVEL', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (34, '3.017', 'DUPLICATA PAGA - DINHEIRO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (35, '4.001', 'VEÍCULOS', 'Débito', 4);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (36, '4.002', 'CONSTRUÇÃO', 'Débito', 4);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (37, '4.003', 'MAQUINAS E EQUIPAMENTOS', 'Débito', 4);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (38, '4.004', 'MOVEIS E UTENSÍLIOS', 'Débito', 4);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (39, '4.005', 'FERRAMENTAS', 'Débito', 4);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (40, '9.001', 'TRANSFERENCIA ENTRE CONTAS', 'Débito', 5);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (41, '9.002', 'EMPRÉSTIMO TOMADO', 'Crédito', 5);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (42, '9.003', 'PAGAMENTO DE EMPRÉSTIMO', 'Débito', 5);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (43, '9.004', 'DEPÓSITO EM APLICAÇÃO', 'Débito', 5);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (44, '9.005', 'RESGATE DE APLICAÇÃO', 'Crédito', 5);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (45, '9.005', 'REFORÇO DE CAIXA', 'Crédito', 5);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (46, '9.005', 'DEPÓSITO EM CONTA CORRENTE', 'Débito', 5);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (47, '9.006', 'DESCONTO CONCEDIDO', 'Débito', 5);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (48, '1.009', 'DUPLICATA RECEBIDA - DINHEIRO', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (49, '1.010', 'DUPLICATA RECEBIDA - CARTÃO DE DÉBITO', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (50, '1.011', 'DUPLICATA RECEBIDA - CARTÃO DE CRÉDITO', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (51, '1.012', 'DUPLICATA RECEBIDA - CHEQUE', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (52, '1.013', 'DUPLICATA RECEBIDA - BOLETO', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (53, '3.018', 'DUPLICATA PAGA - CARTÃO DE DÉBITO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (54, '3.019', 'DUPLICATA PAGA - CARTÃO DE CRÉDITO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (55, '3.020', 'DUPLICATA PAGA - CHEQUE', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (56, 'INSS', 'INSS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (57, '2.010', 'ASSESSORIA CONTÁBIL', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (58, '5.001', 'VENDA VIA PDV', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (59, '5.002', 'VENDA VIA PEDIDO', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (60, '5.003', 'APORTES OU EMPRÉSIMOS', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (61, '5.004', 'ENTRADAS', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (62, '5.005', 'OUTRAS RECEITAS', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (63, '5.006', 'RENDIMENTO DE APLICAÇÃO BANCÁRIA', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (64, '5.007', 'TRANSFERÊNCIA', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (65, '5.008', 'VALE', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (66, '5.009', 'TEF', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (67, '5.010', 'PAGAMENTO DIGITAL', 'Crédito', 1);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (68, '6.001', 'SAÍDAS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (69, '6.002', 'ABATIMENTOS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (70, '6.003', 'ALUGUEL DE EQUIPAMENTOS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (71, '6.004', 'AMORTIZAÇÃO DE EMPRÉSTIMOS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (72, '6.005', 'ATIVOS E EQUIPAMENTOS PRÓPRIOS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (73, '6.006', 'BENEFÍCIOS SALARIAIS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (74, '6.007', 'BRINDES', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (75, '6.008', 'COMISSÃO DE VENDAS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (76, '6.009', 'CONDOMÍNIO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (77, '6.010', 'CONTABILIDADE', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (78, '6.011', 'DEVOLUÇÕES / ABATIMENTOS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (79, '6.012', 'EMBALAGEM', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (80, '6.013', 'ENCARGOS SALARIAIS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (81, '6.014', 'EVENTOS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (82, '6.015', 'HONORÁRIO ADVOCATÍCIOS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (83, '6.016', 'IMPOSTOS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (84, '6.017', 'IPTU', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (85, '6.018', 'JUROS DE EMPRÉSTIMOS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (86, '6.019', 'LIMPEZA', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (87, '6.020', 'MANUTENÇÃO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (88, '6.021', 'MERCADORIA PARA REVENDA', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (89, '6.022', 'OUTRAS DESPESAS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (90, '6.023', 'PRO LABORE', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (91, '6.024', 'SALÁRIOS', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (92, '6.025', 'SEGURANÇA', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (93, '6.026', 'SERVIÇOS DE ENTREGA', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (94, '6.027', 'TELEFONE CELULAR', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (95, '6.028', 'TV A CABO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (96, '6.029', 'VIAGEM E HOSPEDAGEM', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (97, 'BOL', 'PGTO DE BOLETO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (98, '3.021', 'PGTO DE BOLETO', 'Débito', 3);
INSERT INTO HISTORICO (ID, CHAVE, DESCRICAO, DEBITO_CREDITO, ID_GRUPO)
               VALUES (99, '1.014', 'VENDA - CREDITO DEV/TROCA', 'Débito', 5);

COMMIT WORK;
