INSERT INTO PAGTO_FORMA (ID_PAGTOFORMA, DESCRI, ATIVO, USO_PDV)
                 VALUES (1, 'DINHEIRO', 'S', 'S');
INSERT INTO PAGTO_FORMA (ID_PAGTOFORMA, DESCRI, ATIVO, USO_PDV)
                 VALUES (2, 'CHEQUE', 'S', 'S');
INSERT INTO PAGTO_FORMA (ID_PAGTOFORMA, DESCRI, ATIVO, USO_PDV)
                 VALUES (3, 'CARTÂO DE CRÉDITO', 'S', 'S');
INSERT INTO PAGTO_FORMA (ID_PAGTOFORMA, DESCRI, ATIVO, USO_PDV)
                 VALUES (4, 'CARTÃO DE DÉBITO', 'S', 'S');
INSERT INTO PAGTO_FORMA (ID_PAGTOFORMA, DESCRI, ATIVO, USO_PDV)
                 VALUES (5, 'DEPÓSITO', 'S', 'S');
INSERT INTO PAGTO_FORMA (ID_PAGTOFORMA, DESCRI, ATIVO, USO_PDV)
                 VALUES (6, 'TRANSFERÊNCIA', 'S', 'S');
INSERT INTO PAGTO_FORMA (ID_PAGTOFORMA, DESCRI, ATIVO, USO_PDV)
                 VALUES (7, 'VALE', 'S', 'S');
INSERT INTO PAGTO_FORMA (ID_PAGTOFORMA, DESCRI, ATIVO, USO_PDV)
                 VALUES (8, 'BOLETO BANCÁRIO', 'S', 'S');
INSERT INTO PAGTO_FORMA (ID_PAGTOFORMA, DESCRI, ATIVO, USO_PDV)
                 VALUES (9, 'DEBITO EM CONTA', 'S', 'S');

COMMIT WORK;
