INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (1, 1, 'À VISTA', 1, 0, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 2, 'À VISTA', 1, 0, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 3, '01x (30 Dias)', 1, 0, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 4, '02x (30 Dias)', 2, 30, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 5, '02x (30 e 90 Dias)', 2, 60, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 6, '03x (30 Dias)', 3, 30, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 7, '03x (30,90 e 150 Dias)', 3, 60, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 8, '04x (30 Dias)', 4, 30, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 9, '05x (30 Dias)', 5, 30, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 10, '06x (30 Dias)', 6, 30, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 11, '07x (30 Dias)', 7, 30, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 12, '08x (30 Dias)', 8, 30, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 13, '09x (30 Dias)', 9, 30, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (2, 14, '10x (30 Dias)', 10, 30, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (3, 15, 'À VISTA', 1, 0, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (4, 16, 'À VISTA', 1, 0, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (5, 17, 'À VISTA', 1, 0, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (6, 18, 'À VISTA', 1, 0, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (7, 19, 'À VISTA', 1, 0, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 20, 'À VISTA', 1, 0, 0, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 21, '01 X (7 Dias)', 1, 0, 7, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 22, '01 X (30 Dias)', 1, 0, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 23, '02 X (30 e 60 Dias)', 2, 30, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 24, '03 X (30,60 e 90 Dias)', 3, 30, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 25, '05 X (30,60,90,120 e 150 Dias)', 5, 30, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 26, '02 X (15 e 30 Dias)', 2, 15, 15, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 27, '02 X (30 e 40 Dias)', 2, 10, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 28, '01 X (45 Dias direto)', 1, 0, 45, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 29, '01 X (90 Dias direto)', 1, 0, 90, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 30, '04 X (30,60,90 e 120 Dias)', 4, 30, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (9, 31, '24x', 24, 30, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (9, 32, '36x', 36, 30, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (10, 33, '60 DIAS', 1, 60, 60, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (11, 34, '6x parcelas', 6, 30, 30, 0, 'S', 'N');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 35, '06 X (30, 60, 90, 120, 150, 180) Dias', 6, 30, 30, 0, 'S', NULL);
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (12, 36, '7x', 7, 30, 30, 0, 'S', 'S');
INSERT INTO PAGTO_PARCELAMENTO (ID_PAGTOFORMA, ID, DESCRI, NUM_PARCELAS, INTV_PARCELAS, PRIMEIRA_PARC, ACRESCIMO, USO_COMPRAS, USO_VENDAS)
                        VALUES (8, 37, '07 X (30, 60, 90, 120, 150, 180, 210) Dias', 7, 30, 30, 0, 'S', 'S');

COMMIT WORK;
