CREATE INDEX PDV_RECEBER_IDXDATABAIXA
ON PDV_RECEBER (DT_BAIXA);

SET TERM ^ ;

CREATE OR ALTER trigger pdv_devolucao_ai_estoque for pdv_devolucao
active after insert position 0
AS
begin
  execute procedure PRO_ENTRADA_SAIDA(new.id_produto,new.qtde_baixa,'+') ;
end^

SET TERM ; ^

SET TERM ^ ;

CREATE OR ALTER trigger pdv_devolucao_au_estoque for pdv_devolucao
active after update position 0
AS
begin
  execute procedure PRO_ENTRADA_SAIDA(old.ID_PRODUTO,old.QTDE_BAIXA,'-') ;
  execute procedure PRO_ENTRADA_SAIDA(new.ID_PRODUTO,new.QTDE_BAIXA,'+') ;
end^

SET TERM ; ^

SET TERM ^ ;

CREATE OR ALTER trigger pdv_devolucao_ad_estoque for pdv_devolucao
active after delete position 0
AS
begin
  execute procedure PRO_ENTRADA_SAIDA(old.ID_PRODUTO,old.QTDE_BAIXA,'-') ;
end^

SET TERM ; ^

DROP TRIGGER PDV_DEVOLUCAO_AD_ESTOQUE;

SET TERM ^ ;

CREATE OR ALTER trigger tri_ad_pdv_devolucao_estoque for pdv_devolucao
active after delete position 0
AS
begin
  execute procedure PRO_ENTRADA_SAIDA(old.ID_PRODUTO,old.QTDE_BAIXA,'-') ;
end^

SET TERM ; ^

DROP TRIGGER PDV_DEVOLUCAO_AU_ESTOQUE;

SET TERM ^ ;

CREATE OR ALTER trigger tri_au_pdvdevolucao_estoque for pdv_devolucao
active after update position 0
AS
begin
  execute procedure PRO_ENTRADA_SAIDA(old.ID_PRODUTO,old.QTDE_BAIXA,'-') ;
  execute procedure PRO_ENTRADA_SAIDA(new.ID_PRODUTO,new.QTDE_BAIXA,'+') ;
end^

SET TERM ; ^

DROP TRIGGER PDV_DEVOLUCAO_AI_ESTOQUE;

SET TERM ^ ;

CREATE OR ALTER trigger tri_ai_pdvdevolucao_estoque for pdv_devolucao
active after insert position 0
AS
begin
  execute procedure PRO_ENTRADA_SAIDA(new.id_produto,new.qtde_baixa,'+') ;
end^

SET TERM ; ^

CREATE TABLE PDV_CANCELAMENTO (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    TIPO CHAR(1) NOT NULL,
    ID_VENDA INTEGER NOT NULL,
    ORDEM INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    QTDE NUMERIC(8,3) NOT NULL,
    QTDE_BAIXA NUMERIC(8,3),
    DATA DATE,
    USUARIO VARCHAR(100));

ALTER TABLE PDV_CANCELAMENTO
ADD CONSTRAINT PK_PDV_CANCELAMENTO
PRIMARY KEY (ID);

ALTER TABLE PDV_CANCELAMENTO
ADD CONSTRAINT FK_PDV_CANCELAMENTO_ITEM
FOREIGN KEY (ID_VENDA,TIPO,ORDEM)
REFERENCES PDV_ITENS(ID,TIPO,ORDEM)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE PDV_CANCELAMENTO
ADD CONSTRAINT FK_PDV_CANCELAMENTO_PROD
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTO(CODIGO)
ON DELETE CASCADE
ON UPDATE CASCADE;

SET TERM ^ ;

CREATE trigger tri_ai_pdvcancelamento_estoque for pdv_cancelamento
active after insert position 0
AS
begin
  execute procedure PRO_ENTRADA_SAIDA(new.id_produto,new.qtde_baixa,'+') ;
end^

SET TERM ; ^

SET TERM ^ ;

CREATE trigger tri_ad_pdvcancelamento_estoque for pdv_cancelamento
active after delete position 0
AS
begin
  execute procedure PRO_ENTRADA_SAIDA(old.ID_PRODUTO,old.QTDE_BAIXA,'-') ;
end^

SET TERM ; ^

SET TERM ^ ;

CREATE trigger tri_au_pdvcancelamento_estoque for pdv_cancelamento
active after update position 0
AS
begin
  execute procedure PRO_ENTRADA_SAIDA(old.ID_PRODUTO,old.QTDE_BAIXA,'-') ;
  execute procedure PRO_ENTRADA_SAIDA(new.ID_PRODUTO,new.QTDE_BAIXA,'+') ;
end^

SET TERM ; ^


SET TERM ^ ;

CREATE OR ALTER procedure PRO_ISCREDIARIO (
    TIPO char(1) not null,
    ID integer not null)
returns (
    RETORNO integer not null)
as
declare variable FORMAPAGTO varchar(20);
declare variable DATABAIXA date;
begin
  retorno = 0;
  for select PR.FORMA_PAGTO, PR.DT_BAIXA
      from PDV_RECEBER PR
      where PR.TIPO = :TIPO and
            PR.ID = :ID and
            PR.forma_pagto <> 'DESCONTO'

      union all

      select PRP.FORMA_PAGTO, PRP.DT_BAIXA
      from PDV_RECEBER_PARCIAL PRP
      where PRP.TIPO = :TIPO and
            PRP.ID = :ID

      into :FORMAPAGTO, :DATABAIXA
  do
  begin
    if ((:FORMAPAGTO <> 'CREDIARIO') or (:DATABAIXA is not null)) then
    begin
      retorno = 1;
      suspend;
      exit;
    end
  end
  suspend;
end^

SET TERM ; ^

SET TERM ^ ;

CREATE OR ALTER procedure PRO_MOVIMENTOPRODUTO (
    ID_PROD integer)
returns (
    ENTSAI char(1),
    QTDE numeric(15,3),
    QTDE_FECHADA numeric(15,3),
    DTMOVTO date,
    LOTE varchar(20),
    TIPO_MOVIMENTO varchar(20),
    USUARIO varchar(100),
    ID_PRODUTO integer,
    DESCRI varchar(100),
    TIPO_PRODUTO varchar(20),
    CODBARRA varchar(13),
    ESTOQUE_MINIMO numeric(15,3),
    SIGLA_UM varchar(10))
as
begin
  select A.NOME, A.CODIGO,
         case upper(A.TIPO_PRODUTO)
           when 'PA' then 'Produto Acabado'
           when 'MP' then 'Materia Prima'
           else 'Ambos'
         end TIPO_PRODUTO,
         coalesce(A.EAN_CODBARRA, 0), coalesce(A.QTDE_MINIMA, 0), coalesce(C.SIGLA, B.SIGLA) SIGLA
  from PRODUTO A
  left outer join UNIDADE B on (B.CODIGO = A.COD_UNIDADE)
  left join UNIDADE C on (C.CODIGO = A.CONV_UNIDADE)
  where (A.CODIGO = :ID_PROD)
  into :DESCRI, :ID_PRODUTO, :TIPO_PRODUTO, :CODBARRA, :ESTOQUE_MINIMO, :SIGLA_UM;

  /**************ENTRADA - LOTE ****************/
  for select iif(B.ENTSAI = 'ENTRADA', 'E', 'S') ENTSAI, B.QTDE, B.QTDE_FECHADA, A.EMISSAO, A.LOTE, A.USUARIO,
             'LOTE' TIPO_MOVIMENTO
      from LOTE A
      left outer join LOTE_ITENS B on (B.ID_LOTE = A.LOTE)
      where (B.CODPRO = :ID_PROD)
      into :ENTSAI, :QTDE, :QTDE_FECHADA, :DTMOVTO, :LOTE, :USUARIO, :TIPO_MOVIMENTO
  do
  begin
    suspend;
  end
  /****************SAIDA - LOTE MAT. PRIMA *********************************/
  for select 'S' ENTSAI, B.QTDE, B.QTDE_FECHADA, A.EMISSAO, A.LOTE, A.USUARIO, 'LOTE' TIPO_MOVIMENTO
      from LOTE A
      left outer join LOTE_MATPRIMA B on (B.ID_LOTE = A.LOTE)
      where A.GERA_MATPRIMA = 'S' and
            (B.ID_MATPRIMA = :ID_PROD)
      into :ENTSAI, :QTDE, :QTDE_FECHADA, :DTMOVTO, :LOTE, :USUARIO, :TIPO_MOVIMENTO
  do
  begin
    suspend;
  end

  /****************SAIDA - VENDAS*********************************/
  for select 'S' ENTSAI, B.QTDE, B.QTDE_BAIXA, A.EMISSAO, A.TIPO || '-' || A.ID, C.USU_NOME, 'VENDA' TIPO_MOVIMENTO
      from PDV_MASTER A
      left outer join PDV_ITENS B on (B.TIPO = A.TIPO and
            B.ID = A.ID)
      left outer join USUARIO C on (C.ID_VENDEDOR = A.ID_VENDEDOR)
      where (B.ID_PRODUTO = :ID_PROD)
      into :ENTSAI, :QTDE, :QTDE_FECHADA, :DTMOVTO, :LOTE, :USUARIO, :TIPO_MOVIMENTO
  do
  begin
    suspend;
  end

  /****************ENTRADA - NF*********************************/
  for select 'E' ENTSAI, B.QTDE, B.QTDE, A.EMISSAO, 'NF:' || A.N_NF, C.USU_NOME, 'ENT-NF'
      from NOTA_ENTRADA A
      left outer join NOTA_ENTRADA_ITENS B on (B.ID_NOTAENTRADA = A.ID)
      left outer join USUARIO C on (C.USU_ID = A.ID_USUARIO)
      where (B.ID_PRODUTO = :ID_PROD)
      into :ENTSAI, :QTDE, :QTDE_FECHADA, :DTMOVTO, :LOTE, :USUARIO, :TIPO_MOVIMENTO
  do
  begin
    suspend;
  end

  /****************ENTRADA - DEVOLUCAO PDV*********************************/
  for select 'E' ENTSAI, A.QTDE, A.QTDE_BAIXA, A.data, A.TIPO || '-' || A.ID_VENDA, A.USUARIO,
             'DEV/TROCA' TIPO_MOVIMENTO
      from PDV_DEVOLUCAO A
      where (A.ID_PRODUTO = :ID_PROD)
      into :ENTSAI, :QTDE, :QTDE_FECHADA, :DTMOVTO, :LOTE, :USUARIO, :TIPO_MOVIMENTO
  do
  begin
    suspend;
  end

  /****************ENTRADA - CANCELAMENTO PDV*********************************/
  for select 'E' ENTSAI, A.QTDE, A.QTDE_BAIXA, A.data, A.TIPO || '-' || A.ID_VENDA, A.USUARIO,
             'CANCELADA' TIPO_MOVIMENTO
      from pdv_cancelamento A
      where (A.ID_PRODUTO = :ID_PROD)
      into :ENTSAI, :QTDE, :QTDE_FECHADA, :DTMOVTO, :LOTE, :USUARIO, :TIPO_MOVIMENTO
  do
  begin
    suspend;
  end

end^

SET TERM ; ^









