<<<<<<< HEAD
=======
﻿--Alteracoes em firebird.conf
-- descomentar as linhas
--  AuthServer = Srp
--  AuthClient = Srp, Srp256, Win_Sspi, Legacy_Auth #Windows clients
--  UserManager = Srp
--  
--Reiniciar serviço FB  
--
--Substituir security3.fdb da pasta firebird pelo empty
--
--Executar isql para criar usuario SYSDBA
--  isql.exe
--  connect security3.fdb user SYSDBA;
--  create or alter user SYSDBA password 'X5U$w7GQRku6' using plugin Srp;
--  commit;
--  create or alter user SISTEMA password 'ldesistemas' using plugin Srp;
--  commit;
--  select * from sec$users;
--  quit;
--
--Efetuar o procedimento acima para o banco takano tambem.
--**********************************************************************************************

>>>>>>> master
DROP TABLE CONTROL;

CREATE TABLE CONTROL (
    DB_VERSAO INTEGER NOT NULL,
    EM_MANUTENCAO INTEGER NOT NULL);

COMMENT ON COLUMN CONTROL.EM_MANUTENCAO IS
'1 = em manutencao, 0 = livre';


SET TERM ^ ;

CREATE OR ALTER procedure PRO_GET_SCRIPT (
    VERSAO integer not null)
returns (
    SCRIPT_DDL blob sub_type 1 segment size 80,
    SCRIPT_DML blob sub_type 1 segment size 80)
as
declare variable SQL blob sub_type 1 segment size 80;
begin
  sql = 'select s.ddl, s.dml from script s where s.versao = '||:versao;

   EXECUTE STATEMENT sql
   ON EXTERNAL '127.0.0.1/3060:C:\projetos\bancos\FB30\ldecliente.fdb'
<<<<<<< HEAD
   AS USER 'SYSDBA'
   PASSWORD 'masterkey'
=======
   AS USER 'SISTEMA'
   PASSWORD 'ldesistemas'
   ROLE 'R_SISTEMA'
>>>>>>> master
   INTO :script_ddl,:script_dml;

  suspend;
end^

SET TERM ; ^

<<<<<<< HEAD
=======
SET TERM ^ ;

CREATE OR ALTER procedure PRO_RECEBER_VLLIQ (
    TIPO char(1) not null,
    ID integer not null)
returns (
    VL_LIQ numeric(15,2),
    FORMAS_PAGTO varchar(500))
as
begin
  select sum(iif(PR.ID_HISTORICO in (47, 99), 0, PR.VALOR)) VL,
         list(upper(PR.FORMA_PAGTO) || ': ' || 'R$ ' || PR.VALOR, '  ') FORMAS_PAGTO
  from PDV_RECEBER PR
  where PR.ID = :ID and
        PR.TIPO = :TIPO
  into :VL_LIQ, :FORMAS_PAGTO;
  suspend;
end^

SET TERM ; ^

GRANT CREATE TABLE TO SISTEMA;
GRANT ALTER ANY TABLE TO SISTEMA;
GRANT DROP ANY TABLE TO SISTEMA;
GRANT CREATE VIEW TO SISTEMA;
GRANT ALTER ANY VIEW TO SISTEMA;
GRANT DROP ANY VIEW TO SISTEMA;
GRANT CREATE PROCEDURE TO SISTEMA;
GRANT ALTER ANY PROCEDURE TO SISTEMA;
GRANT DROP ANY PROCEDURE TO SISTEMA;
GRANT CREATE SEQUENCE TO SISTEMA;
GRANT ALTER ANY SEQUENCE TO SISTEMA;
GRANT DROP ANY SEQUENCE TO SISTEMA;
GRANT CREATE EXCEPTION TO SISTEMA;
GRANT ALTER ANY EXCEPTION TO SISTEMA;
GRANT DROP ANY EXCEPTION TO SISTEMA;

CREATE ROLE R_SISTEMA;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CAIXA TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CAIXA_ABERT_FECH TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CAIXA_APURACAO_VALORES TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CAIXA_ENT_SAI TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CEST TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CFOP TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CHEQUE TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CIDADE TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CLIENTE TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CONDPAGTO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CONTA_BANCARIA TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON CONTROL TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DEL_PDV_RECEBER TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON EMPRESA TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ESTADO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON FABRICANTE TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON FUNCIONARIO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON GRUPO_FABRICANTE TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON GRUPO_PROD TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON HISTORICO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON HISTORICO_GRUPO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON LANCAMENTO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON LOG_BAIXA_RESTAURA TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON LOTE TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON LOTE_ITENS TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON LOTE_MATPRIMA TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON NATOPERACAO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON NCM TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON NOTA_ENTRADA TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON NOTA_ENTRADA_ANEXO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON NOTA_ENTRADA_ITENS TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON NOTA_ENTRADA_PAGAR TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON NOTA_ENTRADA_PARCIAL TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ORCAMENTO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ORCAMENTO_ITEM TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ORCAMENTO_PAGTO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PAGTO_FORMA TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PAGTO_PARCELAMENTO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PAIS TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PDV_CANCELAMENTO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PDV_DEVOLUCAO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PDV_ITENS TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PDV_MASTER TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PDV_RECEBER TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PDV_RECEBER_PARCIAL TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PEDIDO_VENDA TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PEDIDO_VENDAITENS TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PEDIDO_VENDAPAGAR TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PRECOCUSTO_HISTORICO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PRECOVENDA_HISTORICO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PRODUTO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PRODUTO_COMPOSICAO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON PRODUTO_FORNECEDOR TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON RAMO_ATIVIDADE TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON REPRESENTANTE TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON SUBGRUPO_PROD TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TRANSPORTADORA TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON UNIDADE TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON USUARIO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON USUARIO_GRUPO TO R_SISTEMA;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON VW_FORMAPAGTO TO R_SISTEMA;
GRANT EXECUTE ON PROCEDURE PRO_ENTRADA_SAIDA TO R_SISTEMA;
GRANT EXECUTE ON PROCEDURE PRO_GET_SCRIPT TO R_SISTEMA;
GRANT EXECUTE ON PROCEDURE PRO_HIST_PRECOCUSTO TO R_SISTEMA;
GRANT EXECUTE ON PROCEDURE PRO_HIST_PRECOVENDA TO R_SISTEMA;
GRANT EXECUTE ON PROCEDURE PRO_ISCREDIARIO TO R_SISTEMA;
GRANT EXECUTE ON PROCEDURE PRO_MOVIMENTOPRODUTO TO R_SISTEMA;
GRANT EXECUTE ON PROCEDURE PRO_SONUMEROS TO R_SISTEMA;
GRANT EXECUTE ON PROCEDURE PRO_TOT_DUPLICATAS TO R_SISTEMA;
GRANT EXECUTE ON PROCEDURE PRO_ULTIMAVENDA TO R_SISTEMA;
GRANT EXECUTE ON PROCEDURE PRO_UPDATE_DEBITO_CLIENTE TO R_SISTEMA;
GRANT EXECUTE ON PROCEDURE PRO_UPD_PRODUTO_CUSTO TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_ATENDIMENTO_ID TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_CAIXA TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_CAIXA_ABERT_FECH TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_CAIXA_APURACAO_VALORES TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_CAIXA_ENT_SAI TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_CEST_ID TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_CIDADES_ID TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_CLIENTE TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_CONDPAGTO TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_CONTABANCARIA TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_HISTORICO TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_HISTORICO_GRUPO TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_HIS_PRECOCUSTO TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_LANCAMENTO TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_LOTE TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_LOTE_ITENS TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_LOTE_MATPRIMA TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_NCM_ID TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_NOTAENTRADA TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_NOTAENTRADA_ITENS TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_ORCAMENTO TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_PAGTOFORMA TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_PAGTOPARCELAMENTO TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_PEDIDOVENDA TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_PRAZO_PAGAMENTO_ID TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_PRAZO_PAGAMENTO_PARCELA_ID TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_PRECOHISTORICO TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_PRODUTO TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_RECEBER_PARCIAL TO R_SISTEMA;
GRANT USAGE ON SEQUENCE GEN_UNIDADE TO R_SISTEMA;

grant R_SISTEMA to SISTEMA;




>>>>>>> master


