SELECT r.CODIGO, r.NOME, r.PRECO_VENDA, r.COD_UNIDADE, r.COD_CENARIO,
    r.QTDE_ESTOQUE, r.PRECO_CUSTO, r.ESTIMA_PRODUCAO, r.PESO_BRUTO,
    r.PESO_LIQUIDO, r.EAN_CODBARRA, r.COD_FABRICANTE, r.COD_GRUPO,
    r.COD_SUBGRUPO, r.DESCRICAO, r.COD_NCM, r.TIPO_PRODUTO, r.QTDE_MINIMA,
    r.CONV_UNIDADE, r.CONV_QTDE, r.CONV_PRECO
FROM PRODUTO r;


update PRODUTO A
SET A.QTDE_ESTOQUE = (select  coalesce (sum(iif(b.ENTSAI = 'S',b.QTDE_FECHADA*-1,b.QTDE_FECHADA)),0) from PRO_MOVIMENTOPRODUTO(a.CODIGO) b)